/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { apiKeysDelete } from "../funcs/apiKeysDelete.js";
import { apiKeysRevoke } from "../funcs/apiKeysRevoke.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class ApiKeys extends ClientSDK {
  /**
   * Revoke an API key
   *
   * @remarks
   * Revoke (deactivate) an API key.
   */
  async revoke(
    request: operations.RevokeApiKeyRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(apiKeysRevoke(
      this,
      request,
      options,
    ));
  }

  /**
   * Permanently delete an API key
   *
   * @remarks
   * Permanently delete an API key from the system.
   */
  async delete(
    request: operations.DeleteApiKeyRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(apiKeysDelete(
      this,
      request,
      options,
    ));
  }
}
