/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { checkinsGet } from "../funcs/checkinsGet.js";
import { checkinsList } from "../funcs/checkinsList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Checkins extends ClientSDK {
  /**
   * Get a list of all check-ins
   */
  async list(
    request: operations.ListCheckinsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListCheckinsResponse>> {
    return unwrapResultIterator(checkinsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a check-in by ID
   */
  async get(
    request: operations.GetCheckinRequest,
    options?: RequestOptions,
  ): Promise<components.Checkin> {
    return unwrapAsync(checkinsGet(
      this,
      request,
      options,
    ));
  }
}
