/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { companiesGet } from "../funcs/companiesGet.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Companies extends ClientSDK {
  /**
   * Get company details associated with the API key
   */
  async get(
    options?: RequestOptions,
  ): Promise<components.Company> {
    return unwrapAsync(companiesGet(
      this,
      options,
    ));
  }
}
