/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGet } from "../funcs/customersGet.js";
import { customersList } from "../funcs/customersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { Customer } from "../models/components/customer.js";
import { GetCustomerRequest } from "../models/operations/getcustomer.js";
import {
  ListCustomersRequest,
  ListCustomersResponse,
} from "../models/operations/listcustomers.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Customers extends ClientSDK {
  /**
   * Get a list of all customers in a
   */
  async list(
    request: ListCustomersRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<ListCustomersResponse>> {
    return unwrapResultIterator(customersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer by ID
   */
  async get(
    request: GetCustomerRequest,
    options?: RequestOptions,
  ): Promise<Customer> {
    return unwrapAsync(customersGet(
      this,
      request,
      options,
    ));
  }
}
