/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersGet } from "../funcs/customersGet.js";
import { customersList } from "../funcs/customersList.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Customers extends ClientSDK {
  /**
   * Get a list of all customers in a
   */
  async list(
    request: operations.ListCustomersRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListCustomersResponse>> {
    return unwrapResultIterator(customersList(
      this,
      request,
      options,
    ));
  }

  /**
   * Get a customer by ID
   */
  async get(
    request: operations.GetCustomerRequest,
    options?: RequestOptions,
  ): Promise<components.Customer> {
    return unwrapAsync(customersGet(
      this,
      request,
      options,
    ));
  }
}
