/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesEmailSend } from "../funcs/messagesEmailSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Email extends ClientSDK {
  /**
   * Send an email
   */
  async send(
    request: operations.SendEmailRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesEmailSend(
      this,
      request,
      options,
    ));
  }
}
