/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { appsInstallsGet } from "../funcs/appsInstallsGet.js";
import { appsInstallsHardDelete } from "../funcs/appsInstallsHardDelete.js";
import { appsInstallsList } from "../funcs/appsInstallsList.js";
import { appsInstallsUninstall } from "../funcs/appsInstallsUninstall.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Installs extends ClientSDK {
  /**
   * List all installs of a specific app
   */
  async list(
    request: operations.ListAppInstallsRequest,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListAppInstallsResponse>> {
    return unwrapResultIterator(appsInstallsList(
      this,
      request,
      options,
    ));
  }

  /**
   * Soft uninstall an app (mark it as uninstalled but retain data)
   */
  async uninstall(
    request: operations.UninstallAppRequest,
    options?: RequestOptions,
  ): Promise<components.AppInstall> {
    return unwrapAsync(appsInstallsUninstall(
      this,
      request,
      options,
    ));
  }

  /**
   * Hard delete an app (remove all data)
   */
  async hardDelete(
    request: operations.DeleteAppInstallRequest,
    options?: RequestOptions,
  ): Promise<components.AppInstall> {
    return unwrapAsync(appsInstallsHardDelete(
      this,
      request,
      options,
    ));
  }

  /**
   * Get details of a specific app install
   */
  async get(
    request: operations.GetAppInstallRequest,
    options?: RequestOptions,
  ): Promise<components.AppInstall> {
    return unwrapAsync(appsInstallsGet(
      this,
      request,
      options,
    ));
  }
}
