/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { Email } from "./email.js";
import { Notifications } from "./notifications.js";
import { Push } from "./push.js";

export class Messages extends ClientSDK {
  private _email?: Email;
  get email(): Email {
    return (this._email ??= new Email(this._options));
  }

  private _notifications?: Notifications;
  get notifications(): Notifications {
    return (this._notifications ??= new Notifications(this._options));
  }

  private _push?: Push;
  get push(): Push {
    return (this._push ??= new Push(this._options));
  }
}
