/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesNotificationsSendPing } from "../funcs/messagesNotificationsSendPing.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Notifications extends ClientSDK {
  /**
   * Send a ping notification via Ably Realtime
   */
  async sendPing(
    request: operations.SendPingRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesNotificationsSendPing(
      this,
      request,
      options,
    ));
  }
}
