/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesPushSend } from "../funcs/messagesPushSend.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import { SendPushRequestBody } from "../models/operations/sendpush.js";
import { unwrapAsync } from "../types/fp.js";

export class Push extends ClientSDK {
  /**
   * Send a push notification
   */
  async send(
    request: SendPushRequestBody,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesPushSend(
      this,
      request,
      options,
    ));
  }
}
