/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreate } from "../funcs/webhooksCreate.js";
import { webhooksDelete } from "../funcs/webhooksDelete.js";
import { webhooksGet } from "../funcs/webhooksGet.js";
import { webhooksList } from "../funcs/webhooksList.js";
import { webhooksUpdate } from "../funcs/webhooksUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * Create a new webhook to subscribe to one or more events
   */
  async create(
    request: operations.CreateWebhookRequestBody,
    options?: RequestOptions,
  ): Promise<components.Webhook> {
    return unwrapAsync(webhooksCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * List all registered webhooks
   */
  async list(
    options?: RequestOptions,
  ): Promise<components.Webhook> {
    return unwrapAsync(webhooksList(
      this,
      options,
    ));
  }

  /**
   * Get details of a specific webhook
   */
  async get(
    request: operations.GetWebhookRequest,
    options?: RequestOptions,
  ): Promise<components.Webhook> {
    return unwrapAsync(webhooksGet(
      this,
      request,
      options,
    ));
  }

  /**
   * Update the URL or events for an existing webhook
   */
  async update(
    request: operations.UpdateWebhookRequest,
    options?: RequestOptions,
  ): Promise<components.Webhook> {
    return unwrapAsync(webhooksUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete a specific webhook
   */
  async delete(
    request: operations.DeleteWebhookRequest,
    options?: RequestOptions,
  ): Promise<operations.DeleteWebhookResponseBody> {
    return unwrapAsync(webhooksDelete(
      this,
      request,
      options,
    ));
  }
}
