workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    pushpress-ts-OAS:
        inputs:
            - location: /Users/katrinasanzi/pushpress/openapi.draft.yaml
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
            - location: /Users/katrinasanzi/pushpress/.speakeasy/speakeasy-suggest-error-types.yaml
        registry:
            location: registry.speakeasyapi.dev/katrina/katrina/pushpress-ts-oas
targets:
    pushpress-ts:
        target: typescript
        source: pushpress-ts-OAS
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/katrina/katrina/pushpress-ts-oas-code-samples
            blocking: false
