/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateApiKeyGlobals = {
  companyId?: string | undefined;
};

export type CreateApiKeyRequestBody = {
  /**
   * The ID of the company for which to create the API key
   */
  company: string;
};

/** @internal */
export const CreateApiKeyGlobals$inboundSchema: z.ZodType<
  CreateApiKeyGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type CreateApiKeyGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const CreateApiKeyGlobals$outboundSchema: z.ZodType<
  CreateApiKeyGlobals$Outbound,
  z.ZodTypeDef,
  CreateApiKeyGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateApiKeyGlobals$ {
  /** @deprecated use `CreateApiKeyGlobals$inboundSchema` instead. */
  export const inboundSchema = CreateApiKeyGlobals$inboundSchema;
  /** @deprecated use `CreateApiKeyGlobals$outboundSchema` instead. */
  export const outboundSchema = CreateApiKeyGlobals$outboundSchema;
  /** @deprecated use `CreateApiKeyGlobals$Outbound` instead. */
  export type Outbound = CreateApiKeyGlobals$Outbound;
}

export function createApiKeyGlobalsToJSON(
  createApiKeyGlobals: CreateApiKeyGlobals,
): string {
  return JSON.stringify(
    CreateApiKeyGlobals$outboundSchema.parse(createApiKeyGlobals),
  );
}

export function createApiKeyGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyGlobals' from JSON`,
  );
}

/** @internal */
export const CreateApiKeyRequestBody$inboundSchema: z.ZodType<
  CreateApiKeyRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string(),
});

/** @internal */
export type CreateApiKeyRequestBody$Outbound = {
  company: string;
};

/** @internal */
export const CreateApiKeyRequestBody$outboundSchema: z.ZodType<
  CreateApiKeyRequestBody$Outbound,
  z.ZodTypeDef,
  CreateApiKeyRequestBody
> = z.object({
  company: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateApiKeyRequestBody$ {
  /** @deprecated use `CreateApiKeyRequestBody$inboundSchema` instead. */
  export const inboundSchema = CreateApiKeyRequestBody$inboundSchema;
  /** @deprecated use `CreateApiKeyRequestBody$outboundSchema` instead. */
  export const outboundSchema = CreateApiKeyRequestBody$outboundSchema;
  /** @deprecated use `CreateApiKeyRequestBody$Outbound` instead. */
  export type Outbound = CreateApiKeyRequestBody$Outbound;
}

export function createApiKeyRequestBodyToJSON(
  createApiKeyRequestBody: CreateApiKeyRequestBody,
): string {
  return JSON.stringify(
    CreateApiKeyRequestBody$outboundSchema.parse(createApiKeyRequestBody),
  );
}

export function createApiKeyRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<CreateApiKeyRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateApiKeyRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateApiKeyRequestBody' from JSON`,
  );
}
