/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteWebhookGlobals = {
  companyId?: string | undefined;
};

export type DeleteWebhookRequest = {
  webhookId: string;
};

/**
 * Webhook deleted successfully
 */
export type DeleteWebhookResponseBody = {
  message?: string | undefined;
  /**
   * Unix timestamp of the deletion event
   */
  deleted?: number | undefined;
};

/** @internal */
export const DeleteWebhookGlobals$inboundSchema: z.ZodType<
  DeleteWebhookGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type DeleteWebhookGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const DeleteWebhookGlobals$outboundSchema: z.ZodType<
  DeleteWebhookGlobals$Outbound,
  z.ZodTypeDef,
  DeleteWebhookGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWebhookGlobals$ {
  /** @deprecated use `DeleteWebhookGlobals$inboundSchema` instead. */
  export const inboundSchema = DeleteWebhookGlobals$inboundSchema;
  /** @deprecated use `DeleteWebhookGlobals$outboundSchema` instead. */
  export const outboundSchema = DeleteWebhookGlobals$outboundSchema;
  /** @deprecated use `DeleteWebhookGlobals$Outbound` instead. */
  export type Outbound = DeleteWebhookGlobals$Outbound;
}

export function deleteWebhookGlobalsToJSON(
  deleteWebhookGlobals: DeleteWebhookGlobals,
): string {
  return JSON.stringify(
    DeleteWebhookGlobals$outboundSchema.parse(deleteWebhookGlobals),
  );
}

export function deleteWebhookGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWebhookGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWebhookGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWebhookGlobals' from JSON`,
  );
}

/** @internal */
export const DeleteWebhookRequest$inboundSchema: z.ZodType<
  DeleteWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "webhook_id": "webhookId",
  });
});

/** @internal */
export type DeleteWebhookRequest$Outbound = {
  webhook_id: string;
};

/** @internal */
export const DeleteWebhookRequest$outboundSchema: z.ZodType<
  DeleteWebhookRequest$Outbound,
  z.ZodTypeDef,
  DeleteWebhookRequest
> = z.object({
  webhookId: z.string(),
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWebhookRequest$ {
  /** @deprecated use `DeleteWebhookRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteWebhookRequest$inboundSchema;
  /** @deprecated use `DeleteWebhookRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteWebhookRequest$outboundSchema;
  /** @deprecated use `DeleteWebhookRequest$Outbound` instead. */
  export type Outbound = DeleteWebhookRequest$Outbound;
}

export function deleteWebhookRequestToJSON(
  deleteWebhookRequest: DeleteWebhookRequest,
): string {
  return JSON.stringify(
    DeleteWebhookRequest$outboundSchema.parse(deleteWebhookRequest),
  );
}

export function deleteWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWebhookRequest' from JSON`,
  );
}

/** @internal */
export const DeleteWebhookResponseBody$inboundSchema: z.ZodType<
  DeleteWebhookResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string().optional(),
  deleted: z.number().int().optional(),
});

/** @internal */
export type DeleteWebhookResponseBody$Outbound = {
  message?: string | undefined;
  deleted?: number | undefined;
};

/** @internal */
export const DeleteWebhookResponseBody$outboundSchema: z.ZodType<
  DeleteWebhookResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteWebhookResponseBody
> = z.object({
  message: z.string().optional(),
  deleted: z.number().int().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteWebhookResponseBody$ {
  /** @deprecated use `DeleteWebhookResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteWebhookResponseBody$inboundSchema;
  /** @deprecated use `DeleteWebhookResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteWebhookResponseBody$outboundSchema;
  /** @deprecated use `DeleteWebhookResponseBody$Outbound` instead. */
  export type Outbound = DeleteWebhookResponseBody$Outbound;
}

export function deleteWebhookResponseBodyToJSON(
  deleteWebhookResponseBody: DeleteWebhookResponseBody,
): string {
  return JSON.stringify(
    DeleteWebhookResponseBody$outboundSchema.parse(deleteWebhookResponseBody),
  );
}

export function deleteWebhookResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteWebhookResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteWebhookResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteWebhookResponseBody' from JSON`,
  );
}
