/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetAppRequest = {
  appId: string;
};

/** @internal */
export const GetAppRequest$inboundSchema: z.ZodType<
  GetAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
  });
});

/** @internal */
export type GetAppRequest$Outbound = {
  app_id: string;
};

/** @internal */
export const GetAppRequest$outboundSchema: z.ZodType<
  GetAppRequest$Outbound,
  z.ZodTypeDef,
  GetAppRequest
> = z.object({
  appId: z.string(),
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAppRequest$ {
  /** @deprecated use `GetAppRequest$inboundSchema` instead. */
  export const inboundSchema = GetAppRequest$inboundSchema;
  /** @deprecated use `GetAppRequest$outboundSchema` instead. */
  export const outboundSchema = GetAppRequest$outboundSchema;
  /** @deprecated use `GetAppRequest$Outbound` instead. */
  export type Outbound = GetAppRequest$Outbound;
}

export function getAppRequestToJSON(getAppRequest: GetAppRequest): string {
  return JSON.stringify(GetAppRequest$outboundSchema.parse(getAppRequest));
}

export function getAppRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetAppRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetAppRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetAppRequest' from JSON`,
  );
}
