/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCustomerGlobals = {
  companyId?: string | undefined;
};

export type GetCustomerRequest = {
  id: string;
};

/** @internal */
export const GetCustomerGlobals$inboundSchema: z.ZodType<
  GetCustomerGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type GetCustomerGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const GetCustomerGlobals$outboundSchema: z.ZodType<
  GetCustomerGlobals$Outbound,
  z.ZodTypeDef,
  GetCustomerGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomerGlobals$ {
  /** @deprecated use `GetCustomerGlobals$inboundSchema` instead. */
  export const inboundSchema = GetCustomerGlobals$inboundSchema;
  /** @deprecated use `GetCustomerGlobals$outboundSchema` instead. */
  export const outboundSchema = GetCustomerGlobals$outboundSchema;
  /** @deprecated use `GetCustomerGlobals$Outbound` instead. */
  export type Outbound = GetCustomerGlobals$Outbound;
}

export function getCustomerGlobalsToJSON(
  getCustomerGlobals: GetCustomerGlobals,
): string {
  return JSON.stringify(
    GetCustomerGlobals$outboundSchema.parse(getCustomerGlobals),
  );
}

export function getCustomerGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerGlobals' from JSON`,
  );
}

/** @internal */
export const GetCustomerRequest$inboundSchema: z.ZodType<
  GetCustomerRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type GetCustomerRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCustomerRequest$outboundSchema: z.ZodType<
  GetCustomerRequest$Outbound,
  z.ZodTypeDef,
  GetCustomerRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCustomerRequest$ {
  /** @deprecated use `GetCustomerRequest$inboundSchema` instead. */
  export const inboundSchema = GetCustomerRequest$inboundSchema;
  /** @deprecated use `GetCustomerRequest$outboundSchema` instead. */
  export const outboundSchema = GetCustomerRequest$outboundSchema;
  /** @deprecated use `GetCustomerRequest$Outbound` instead. */
  export type Outbound = GetCustomerRequest$Outbound;
}

export function getCustomerRequestToJSON(
  getCustomerRequest: GetCustomerRequest,
): string {
  return JSON.stringify(
    GetCustomerRequest$outboundSchema.parse(getCustomerRequest),
  );
}

export function getCustomerRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCustomerRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCustomerRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCustomerRequest' from JSON`,
  );
}
