/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetCompanyGlobals = {
  companyId?: string | undefined;
};

export type GetCompanyRequest = {};

/** @internal */
export const GetCompanyGlobals$inboundSchema: z.ZodType<
  GetCompanyGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type GetCompanyGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const GetCompanyGlobals$outboundSchema: z.ZodType<
  GetCompanyGlobals$Outbound,
  z.ZodTypeDef,
  GetCompanyGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompanyGlobals$ {
  /** @deprecated use `GetCompanyGlobals$inboundSchema` instead. */
  export const inboundSchema = GetCompanyGlobals$inboundSchema;
  /** @deprecated use `GetCompanyGlobals$outboundSchema` instead. */
  export const outboundSchema = GetCompanyGlobals$outboundSchema;
  /** @deprecated use `GetCompanyGlobals$Outbound` instead. */
  export type Outbound = GetCompanyGlobals$Outbound;
}

export function getCompanyGlobalsToJSON(
  getCompanyGlobals: GetCompanyGlobals,
): string {
  return JSON.stringify(
    GetCompanyGlobals$outboundSchema.parse(getCompanyGlobals),
  );
}

export function getCompanyGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<GetCompanyGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompanyGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompanyGlobals' from JSON`,
  );
}

/** @internal */
export const GetCompanyRequest$inboundSchema: z.ZodType<
  GetCompanyRequest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type GetCompanyRequest$Outbound = {};

/** @internal */
export const GetCompanyRequest$outboundSchema: z.ZodType<
  GetCompanyRequest$Outbound,
  z.ZodTypeDef,
  GetCompanyRequest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetCompanyRequest$ {
  /** @deprecated use `GetCompanyRequest$inboundSchema` instead. */
  export const inboundSchema = GetCompanyRequest$inboundSchema;
  /** @deprecated use `GetCompanyRequest$outboundSchema` instead. */
  export const outboundSchema = GetCompanyRequest$outboundSchema;
  /** @deprecated use `GetCompanyRequest$Outbound` instead. */
  export type Outbound = GetCompanyRequest$Outbound;
}

export function getCompanyRequestToJSON(
  getCompanyRequest: GetCompanyRequest,
): string {
  return JSON.stringify(
    GetCompanyRequest$outboundSchema.parse(getCompanyRequest),
  );
}

export function getCompanyRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetCompanyRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetCompanyRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetCompanyRequest' from JSON`,
  );
}
