/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type InstallAppGlobals = {
  companyId?: string | undefined;
};

export type InstallAppRequestBody = {
  /**
   * The ID of the company on which to install the app
   */
  company: string;
};

export type InstallAppRequest = {
  appId: string;
  requestBody: InstallAppRequestBody;
};

/** @internal */
export const InstallAppGlobals$inboundSchema: z.ZodType<
  InstallAppGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type InstallAppGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const InstallAppGlobals$outboundSchema: z.ZodType<
  InstallAppGlobals$Outbound,
  z.ZodTypeDef,
  InstallAppGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallAppGlobals$ {
  /** @deprecated use `InstallAppGlobals$inboundSchema` instead. */
  export const inboundSchema = InstallAppGlobals$inboundSchema;
  /** @deprecated use `InstallAppGlobals$outboundSchema` instead. */
  export const outboundSchema = InstallAppGlobals$outboundSchema;
  /** @deprecated use `InstallAppGlobals$Outbound` instead. */
  export type Outbound = InstallAppGlobals$Outbound;
}

export function installAppGlobalsToJSON(
  installAppGlobals: InstallAppGlobals,
): string {
  return JSON.stringify(
    InstallAppGlobals$outboundSchema.parse(installAppGlobals),
  );
}

export function installAppGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<InstallAppGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstallAppGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallAppGlobals' from JSON`,
  );
}

/** @internal */
export const InstallAppRequestBody$inboundSchema: z.ZodType<
  InstallAppRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  company: z.string(),
});

/** @internal */
export type InstallAppRequestBody$Outbound = {
  company: string;
};

/** @internal */
export const InstallAppRequestBody$outboundSchema: z.ZodType<
  InstallAppRequestBody$Outbound,
  z.ZodTypeDef,
  InstallAppRequestBody
> = z.object({
  company: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallAppRequestBody$ {
  /** @deprecated use `InstallAppRequestBody$inboundSchema` instead. */
  export const inboundSchema = InstallAppRequestBody$inboundSchema;
  /** @deprecated use `InstallAppRequestBody$outboundSchema` instead. */
  export const outboundSchema = InstallAppRequestBody$outboundSchema;
  /** @deprecated use `InstallAppRequestBody$Outbound` instead. */
  export type Outbound = InstallAppRequestBody$Outbound;
}

export function installAppRequestBodyToJSON(
  installAppRequestBody: InstallAppRequestBody,
): string {
  return JSON.stringify(
    InstallAppRequestBody$outboundSchema.parse(installAppRequestBody),
  );
}

export function installAppRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<InstallAppRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstallAppRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallAppRequestBody' from JSON`,
  );
}

/** @internal */
export const InstallAppRequest$inboundSchema: z.ZodType<
  InstallAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
  RequestBody: z.lazy(() => InstallAppRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type InstallAppRequest$Outbound = {
  app_id: string;
  RequestBody: InstallAppRequestBody$Outbound;
};

/** @internal */
export const InstallAppRequest$outboundSchema: z.ZodType<
  InstallAppRequest$Outbound,
  z.ZodTypeDef,
  InstallAppRequest
> = z.object({
  appId: z.string(),
  requestBody: z.lazy(() => InstallAppRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InstallAppRequest$ {
  /** @deprecated use `InstallAppRequest$inboundSchema` instead. */
  export const inboundSchema = InstallAppRequest$inboundSchema;
  /** @deprecated use `InstallAppRequest$outboundSchema` instead. */
  export const outboundSchema = InstallAppRequest$outboundSchema;
  /** @deprecated use `InstallAppRequest$Outbound` instead. */
  export type Outbound = InstallAppRequest$Outbound;
}

export function installAppRequestToJSON(
  installAppRequest: InstallAppRequest,
): string {
  return JSON.stringify(
    InstallAppRequest$outboundSchema.parse(installAppRequest),
  );
}

export function installAppRequestFromJSON(
  jsonString: string,
): SafeParseResult<InstallAppRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InstallAppRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InstallAppRequest' from JSON`,
  );
}
