/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UninstallAppGlobals = {
  companyId?: string | undefined;
};

export type UninstallAppRequest = {
  appId: string;
  installId: string;
};

/** @internal */
export const UninstallAppGlobals$inboundSchema: z.ZodType<
  UninstallAppGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type UninstallAppGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const UninstallAppGlobals$outboundSchema: z.ZodType<
  UninstallAppGlobals$Outbound,
  z.ZodTypeDef,
  UninstallAppGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UninstallAppGlobals$ {
  /** @deprecated use `UninstallAppGlobals$inboundSchema` instead. */
  export const inboundSchema = UninstallAppGlobals$inboundSchema;
  /** @deprecated use `UninstallAppGlobals$outboundSchema` instead. */
  export const outboundSchema = UninstallAppGlobals$outboundSchema;
  /** @deprecated use `UninstallAppGlobals$Outbound` instead. */
  export type Outbound = UninstallAppGlobals$Outbound;
}

export function uninstallAppGlobalsToJSON(
  uninstallAppGlobals: UninstallAppGlobals,
): string {
  return JSON.stringify(
    UninstallAppGlobals$outboundSchema.parse(uninstallAppGlobals),
  );
}

export function uninstallAppGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UninstallAppGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UninstallAppGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UninstallAppGlobals' from JSON`,
  );
}

/** @internal */
export const UninstallAppRequest$inboundSchema: z.ZodType<
  UninstallAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app_id: z.string(),
  install_id: z.string(),
}).transform((v) => {
  return remap$(v, {
    "app_id": "appId",
    "install_id": "installId",
  });
});

/** @internal */
export type UninstallAppRequest$Outbound = {
  app_id: string;
  install_id: string;
};

/** @internal */
export const UninstallAppRequest$outboundSchema: z.ZodType<
  UninstallAppRequest$Outbound,
  z.ZodTypeDef,
  UninstallAppRequest
> = z.object({
  appId: z.string(),
  installId: z.string(),
}).transform((v) => {
  return remap$(v, {
    appId: "app_id",
    installId: "install_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UninstallAppRequest$ {
  /** @deprecated use `UninstallAppRequest$inboundSchema` instead. */
  export const inboundSchema = UninstallAppRequest$inboundSchema;
  /** @deprecated use `UninstallAppRequest$outboundSchema` instead. */
  export const outboundSchema = UninstallAppRequest$outboundSchema;
  /** @deprecated use `UninstallAppRequest$Outbound` instead. */
  export type Outbound = UninstallAppRequest$Outbound;
}

export function uninstallAppRequestToJSON(
  uninstallAppRequest: UninstallAppRequest,
): string {
  return JSON.stringify(
    UninstallAppRequest$outboundSchema.parse(uninstallAppRequest),
  );
}

export function uninstallAppRequestFromJSON(
  jsonString: string,
): SafeParseResult<UninstallAppRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UninstallAppRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UninstallAppRequest' from JSON`,
  );
}
