/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateWebhookGlobals = {
  companyId?: string | undefined;
};

export type UpdateWebhookRequest = {
  webhookId: string;
  requestBody?: any | undefined;
};

/** @internal */
export const UpdateWebhookGlobals$inboundSchema: z.ZodType<
  UpdateWebhookGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  companyId: z.string().optional(),
});

/** @internal */
export type UpdateWebhookGlobals$Outbound = {
  companyId?: string | undefined;
};

/** @internal */
export const UpdateWebhookGlobals$outboundSchema: z.ZodType<
  UpdateWebhookGlobals$Outbound,
  z.ZodTypeDef,
  UpdateWebhookGlobals
> = z.object({
  companyId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookGlobals$ {
  /** @deprecated use `UpdateWebhookGlobals$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookGlobals$inboundSchema;
  /** @deprecated use `UpdateWebhookGlobals$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookGlobals$outboundSchema;
  /** @deprecated use `UpdateWebhookGlobals$Outbound` instead. */
  export type Outbound = UpdateWebhookGlobals$Outbound;
}

export function updateWebhookGlobalsToJSON(
  updateWebhookGlobals: UpdateWebhookGlobals,
): string {
  return JSON.stringify(
    UpdateWebhookGlobals$outboundSchema.parse(updateWebhookGlobals),
  );
}

export function updateWebhookGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookGlobals' from JSON`,
  );
}

/** @internal */
export const UpdateWebhookRequest$inboundSchema: z.ZodType<
  UpdateWebhookRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  webhook_id: z.string(),
  RequestBody: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "webhook_id": "webhookId",
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateWebhookRequest$Outbound = {
  webhook_id: string;
  RequestBody?: any | undefined;
};

/** @internal */
export const UpdateWebhookRequest$outboundSchema: z.ZodType<
  UpdateWebhookRequest$Outbound,
  z.ZodTypeDef,
  UpdateWebhookRequest
> = z.object({
  webhookId: z.string(),
  requestBody: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    webhookId: "webhook_id",
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateWebhookRequest$ {
  /** @deprecated use `UpdateWebhookRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateWebhookRequest$inboundSchema;
  /** @deprecated use `UpdateWebhookRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateWebhookRequest$outboundSchema;
  /** @deprecated use `UpdateWebhookRequest$Outbound` instead. */
  export type Outbound = UpdateWebhookRequest$Outbound;
}

export function updateWebhookRequestToJSON(
  updateWebhookRequest: UpdateWebhookRequest,
): string {
  return JSON.stringify(
    UpdateWebhookRequest$outboundSchema.parse(updateWebhookRequest),
  );
}

export function updateWebhookRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateWebhookRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateWebhookRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateWebhookRequest' from JSON`,
  );
}
