/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Schema representing a company with a pushpress account, whether its a gym, martial arts studio or mermaid swim school
 */
export type Company = {
  /**
   * Unique identifier for the company
   */
  id: string;
  /**
   * Name of the company
   */
  name: string;
  /**
   * Subdomain of the company
   */
  subdomain: string;
  /**
   * Default timezone of the company
   */
  defaultTimezone: string;
  /**
   * Phone number of the company
   */
  phone: string;
  /**
   * Email address of the company
   */
  email: string;
  /**
   * URL of the company
   */
  url?: string | undefined;
};

/** @internal */
export const Company$inboundSchema: z.ZodType<Company, z.ZodTypeDef, unknown> =
  z.object({
    id: z.string(),
    name: z.string(),
    subdomain: z.string(),
    defaultTimezone: z.string(),
    phone: z.string(),
    email: z.string(),
    url: z.string().optional(),
  });

/** @internal */
export type Company$Outbound = {
  id: string;
  name: string;
  subdomain: string;
  defaultTimezone: string;
  phone: string;
  email: string;
  url?: string | undefined;
};

/** @internal */
export const Company$outboundSchema: z.ZodType<
  Company$Outbound,
  z.ZodTypeDef,
  Company
> = z.object({
  id: z.string(),
  name: z.string(),
  subdomain: z.string(),
  defaultTimezone: z.string(),
  phone: z.string(),
  email: z.string(),
  url: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Company$ {
  /** @deprecated use `Company$inboundSchema` instead. */
  export const inboundSchema = Company$inboundSchema;
  /** @deprecated use `Company$outboundSchema` instead. */
  export const outboundSchema = Company$outboundSchema;
  /** @deprecated use `Company$Outbound` instead. */
  export type Outbound = Company$Outbound;
}

export function companyToJSON(company: Company): string {
  return JSON.stringify(Company$outboundSchema.parse(company));
}

export function companyFromJSON(
  jsonString: string,
): SafeParseResult<Company, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Company$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Company' from JSON`,
  );
}
