/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export const EventCheckinType = {
  EventCheckin: "EventCheckin",
} as const;
export type EventCheckinType = ClosedEnum<typeof EventCheckinType>;

export type EventCheckin = {
  /**
   * Name of the checked-in event
   */
  name: string;
  type: EventCheckinType;
  /**
   * Type of the event
   */
  eventType: string;
};

/** @internal */
export const EventCheckinType$inboundSchema: z.ZodNativeEnum<
  typeof EventCheckinType
> = z.nativeEnum(EventCheckinType);

/** @internal */
export const EventCheckinType$outboundSchema: z.ZodNativeEnum<
  typeof EventCheckinType
> = EventCheckinType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EventCheckinType$ {
  /** @deprecated use `EventCheckinType$inboundSchema` instead. */
  export const inboundSchema = EventCheckinType$inboundSchema;
  /** @deprecated use `EventCheckinType$outboundSchema` instead. */
  export const outboundSchema = EventCheckinType$outboundSchema;
}

/** @internal */
export const EventCheckin$inboundSchema: z.ZodType<
  EventCheckin,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
  type: EventCheckinType$inboundSchema,
  eventType: z.string(),
});

/** @internal */
export type EventCheckin$Outbound = {
  name: string;
  type: string;
  eventType: string;
};

/** @internal */
export const EventCheckin$outboundSchema: z.ZodType<
  EventCheckin$Outbound,
  z.ZodTypeDef,
  EventCheckin
> = z.object({
  name: z.string(),
  type: EventCheckinType$outboundSchema,
  eventType: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace EventCheckin$ {
  /** @deprecated use `EventCheckin$inboundSchema` instead. */
  export const inboundSchema = EventCheckin$inboundSchema;
  /** @deprecated use `EventCheckin$outboundSchema` instead. */
  export const outboundSchema = EventCheckin$outboundSchema;
  /** @deprecated use `EventCheckin$Outbound` instead. */
  export type Outbound = EventCheckin$Outbound;
}

export function eventCheckinToJSON(eventCheckin: EventCheckin): string {
  return JSON.stringify(EventCheckin$outboundSchema.parse(eventCheckin));
}

export function eventCheckinFromJSON(
  jsonString: string,
): SafeParseResult<EventCheckin, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventCheckin$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventCheckin' from JSON`,
  );
}
